inherits: ../base.yaml
variant: mtp
device: mps
model:
  attn_type: causal
  use_time_cond: false
  n_mtp_heads: 5
  max_length: 128
train:
  epochs: 2000
  steps: null
  batch_size: 32
  lr: 0.0003
eval:
  every_n_epochs: 10
viz:
  every_n_steps: 500
