inherits: ../base.yaml
variant: diffusion
device: mps
model:
  attn_type: bidirectional
  use_time_cond: true
  max_length: 128
train:
  epochs: 2000
  steps: null
  batch_size: 24
  lr: 0.0003
data:
  train_size: null
  val_size: null
  overfit_text: null
eval:
  every_n_epochs: 10
viz:
  every_n_steps: 500
